# Ceci déclenche le pipeline uniquement lorsque des modifications sont apportées au dossier 'api'.
trigger:
  paths:
    include:
    - api/*

# Ceci définit l'environnement dans lequel votre pipeline s'exécute. Ici, il s'exécute sur une machine virtuelle Ubuntu.
pool:
  vmImage: 'ubuntu-latest'

# Ceci empêche Azure Pipelines de récupérer automatiquement votre dépôt.
checkout: none

steps:
# Cette tâche clone uniquement le dossier 'api' de votre dépôt.
- script: |
    git init api
    cd api
    git remote add origin https://github.com/juliengatineau/OpenClassroom.git
    git config core.sparseCheckout true
    echo "api/*" > .git/info/sparse-checkout
    git pull origin main
  displayName: 'Clone api directory'

# Cette tâche configure la version de Python utilisée par le pipeline. Ici, elle est réglée sur Python 3.8.
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true

# Ce script met à jour pip, l'outil d'installation de paquets Python.
- script: |
    python -m pip install --upgrade pip
  displayName: 'Install tools'

# Ce script installe les dépendances de votre projet à partir du fichier 'requirements.txt'.
- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Ce script exécute vos tests unitaires.
- script: |
    python -m unittest test_api.py
  displayName: 'Run tests'