name: CI/CD Pipeline

on:
  push:
    paths:
      - 'api/backend/**'
      - '.github/workflows/main.yml'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        cd api/backend
        pip install -r requirements.txt

    - name: Test the app
      run: |
        echo Testing the app...
        cd api/backend
        pytest test.py

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        pip install azure-cli

    - name: Deploy the app
      run: |
        echo Deploying the app...
        az login --service-principal -u ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }} -p ${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        cd api/backend
        az webapp deployment source config-zip --name projet-7-api --resource-group ressources_rojet_7
        az webapp config set --name projet-7-api --resource-group ressources_rojet_7 --startup-file startup.sh